feat: implement array constructor builtins
trynova/nova pull request #180
Opened 2024-05-13 09:31 UTC by eliassjogreen

This PR implements the array constructor builtin functions according to spec.

Closes #143

2024-05-14 18:08 UTC, aapoalas requested changes
Awesome stuff, thank you for doing this! <3

There's unfortunately a string/integer PropertyKey thing here that we should resolve, caused by a bug in the engine. I left `issue:` comments in those places that should be changed before merging. Note: The comment "notation" comes from [Conventional Comments](https://conventionalcomments.org/).

Anyway, absolutely awesome stuff, thank you so much! <3

2024-05-14 18:08 UTC, aapoalas commented on nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
> +            let fk = Value::try_from(k as f64).unwrap();
**issue:** Same stuff here as above, let's keep using integers and not do the string conversion for property keys.

2024-05-14 18:08 UTC, aapoalas commented on nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
> +        let len_number = Value::try_from(len as f64).unwrap();
**issue:** Same as above, keep integer.

2024-05-14 18:08 UTC, aapoalas commented on nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
> +            let constructor = unsafe { Function::try_from(this_value).unwrap_unchecked() };
**issue:** Same as above, unwrap normally.

2024-05-14 18:08 UTC, aapoalas commented on nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
> +                PropertyKey::from(to_string(agent, Value::try_from(k as f64).unwrap()).unwrap());
**issue:** Same as above, keep integer and avoid string conversion.

2024-05-14 18:16 UTC, eliassjogreen commented on nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
> +/// ### [7.4.10 IfAbruptCloseIterator ( value, iteratorRecord )](https://tc39.es/ecma262/#sec-ifabruptcloseiterator)
It's `7.4.8 IteratorStepValue` that is new I believe :)

2024-05-15 18:26 UTC, aapoalas commented on nova_vm/src/ecmascript/abstract_operations/type_conversion.rs
> +    if argument == BUILTIN_STRING_MEMORY.__0 {
**issue:** This seems wrong: The string `-0` should get turned into `_0`; `__0` would be eg. `--0`.

2024-05-15 18:33 UTC, aapoalas approved these changes
Ooops I was wrong about the string logic. Looks good to me!

Merging after CI says a-okay. Thank you so much <3

2024-05-15 18:39 UTC, merged