feat(ecmascript): remainder and shift operators
trynova/nova pull request #272
Opened 2024-06-30 14:29 UTC by eliassjogreen

- **feat: Add remainder operator**
- **feat: Add left and right shift operators**
- **chore: update expectations**

2024-06-30 18:05 UTC, aapoalas requested changes
Looks good to me except for one probably mistaken import, and then the expectations seem to be off. Might it be that you have so much memory on your machine that it's fine with using 4 GB of RAM in a single array?

2024-06-30 18:05 UTC, aapoalas commented on nova_vm/src/ecmascript/types/language/number.rs
> +use num_traits::PrimInt;
**issue:** This is probably an accidental import from writing `Primitive`?

2024-07-01 15:56 UTC, eliassjogreen commented
Heh yeah, my machine has 32g so I guess it ran without a problem 😅.

2024-07-02 03:55 UTC, aapoalas requested changes
Found one mistaken place.

2024-07-02 03:55 UTC, aapoalas commented on nova_vm/src/ecmascript/types/language/number.rs
> +        let lnum = to_int32(agent, x.into_value()).unwrap();
**issue:** Should be ToUint here

2024-07-02 10:58 UTC, aapoalas approved these changes
Looks good to me, thank you very much! <3

2024-07-02 10:59 UTC, merged