feat(array): Implement `from_slice` to array
trynova/nova pull request #382
Opened 2024-08-06 03:26 UTC by load1n9

2024-08-07 21:33 UTC, andreubotella approved these changes

2024-08-07 21:33 UTC, andreubotella commented on nova_vm/src/ecmascript/builtins/array.rs
> +        let array = agent.heap.create(ArrayHeapData::default());
It'd be better to reserve the left upfront:

```suggestion
        let mut heap_data = ArrayHeapData::default();
        heap_data.elements.reserve(
            &mut agent.heap.elements,
            u32::try_from(elements.len()).unwrap(),
        );
        let array = agent.heap.create(heap_data);
```

2024-08-07 21:36 UTC, andreubotella approved these changes

2024-08-09 18:18 UTC, aapoalas requested changes
Let's go a tad bit lower :)

2024-08-09 18:18 UTC, aapoalas commented on nova_vm/src/ecmascript/builtins/array.rs
> +        for (index, value) in elements.iter().enumerate() {
**issue:** We don't need to use `[[DefineOwnProperty]]` as we know exactly which steps it'll take in this case.

We can skip right to the chase and just do something like this:
```rs
heap_data.elements.as_mut_slice().iter_mut().zip(elements).for_each(|(elements_slot, element) {
  *elements_slot = Some(element.into_value());
});
```
I believe this should compile down to just a memcpy.

2024-09-11 17:19 UTC, aapoalas approved these changes
@andreubotella is absolutely right <3 I switched this to call `create_array_from_list`.

2024-09-11 17:19 UTC, load1n9 commented
LGTM

2024-09-11 17:29 UTC, merged