feat(ecmascript): Add initial version of `Object.groupBy`
trynova/nova pull request #389
Opened 2024-08-13 09:37 UTC by thegreatercurve

Closes #252

2024-08-13 09:39 UTC, thegreatercurve commented
@aapoalas Is there a way of running individual test262 tests to see the runtime errors from the tests which are still crashing?

2024-08-13 09:46 UTC, eliassjogreen commented
> @aapoalas Is there a way of running individual test262 tests to see the runtime errors from the tests which are still crashing?

Running `cargo run --bin test262 -- eval-test path/to/the/test.js` should do the trick. Remember to rebuild the nova cli before running too as the test runner does not do that.

2024-08-13 16:36 UTC, aapoalas commented
> @aapoalas Is there a way of running individual test262 tests to see the runtime errors from the tests which are still crashing?

What I usually do is that I run the `eval-test` command once, copy its output and replace `.../target/debug/nova_cli` with `cargo run` to get automatic cargo builds of `nova_cli` in subsequent runs.

2024-08-13 16:47 UTC, aapoalas requested changes
Some issues made their way in, but overall looks good to me! Thank you very much <3

2024-08-13 16:47 UTC, aapoalas commented on nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
> +    pub(crate) key: Value,
**issue:** This should rather be `PropertyKey`.

2024-08-14 20:27 UTC, thegreatercurve commented
@aapoalas Made the requested changes. The remaining string test which is not passing appears to be an unrelated issue with parsing emoji Unicode chars.

2024-08-15 10:16 UTC, aapoalas commented
> @aapoalas Made the requested changes. I was using the wrong method to pass in the value to the callback.
> 
> The remaining string test which is not passing appears to be an unrelated issue with parsing emoji Unicode chars.

Looks good to me! I had made a mistake when I said that the type in the Group should be PropertyKey: It should only be so in the Property case. The GroupBy function is essentially generic with two variants. I manually split it apart while making the internal helper functions actually generic.

Now we get nice types :)

2024-08-15 10:20 UTC, thegreatercurve commented
@aapoalas Thanks for the additional context and adding the extra variant.

2024-08-15 10:24 UTC, aapoalas approved these changes

2024-08-15 10:24 UTC, merged

2024-08-15 10:24 UTC, aapoalas commented
Again, thank you very much and good job! <3